### ISSUE TITLE
Alpha and Beta states for PDF417 and Aztec respectively

### ISSUE THREAD

**Issue by xtreme-josh-kwan** [TheLevelUp/ZXingObjC#175]
Hey everyone,

I wanted to get an idea of the stability/maturity of the PDF417 and Aztec encoding features at this time as I noticed they are marked as alpha and beta respectively.

I tested out the PDF417 generating functionality and it seemed to work as expected for the most part...

Thanks for the clarification!

**Comment by cwalcott** [comment]
Basically Aztec and PDF417 are labeled alpha and beta because that's how they're labeled in [ZXing](https://github.com/zxing/zxing/), from which ZXingObjC is ported. PDF417 has gotten some improvements recently in ZXing and is now labeled "beta" by them. I'm hoping to port over some of their more recent changes (including to PDF417) so that ZXingObjC will have them too.
