### ISSUE TITLE
Xcode 6.3 Beta error Multiple methods named "initWithType" found with mismatched result

### ISSUE THREAD

**Issue by alandeguz** [TheLevelUp/ZXingObjC#208]
When we try to compile this library with the default settings for iOS 8.3 Beta 4 (Xcode 6.3 Beta 4), the following error is generated.

```
ZXParsedResult.m:30:10: Multiple methods named 'initWithType:' found with mismatched result, parameter type or attributes
```

The `parsedResultWithType` is a class method, and I believe it should be written as follows, which resolves the issue and works with iOS 8.2 (and earlier).

```Objective-C
+ (id)parsedResultWithType:(ZXParsedResultType)type {
  return [[ZXParsedResult alloc] initWithType:type];
}
```

**Comment by cwalcott** [comment]
Thanks!

**Comment by xGoPox** [comment]
Thanks !

**Comment by Fosile** [comment]
Thanks :D

**Comment by Westacular** [comment]
Are you sure this change is really correct? Using `[self alloc]` ensures that if you call `parsedResultWithType:` on a subclass, e.g., `[ZXCalendarParsedResult parsedResultWithType:foo]`, the created object will have that subclass's type. The change made above will cause all calls to this method to return `ZXParsedResult` objects instead. However, I'm not sure if that's actually a problem, since it looks like this method is never called anyway.

An alternate solution is to cast the result of `[self alloc]` to give the type checker the hint it needs to let it ignore other unrelated `initWithType:` methods:
```
+ (id)parsedResultWithType:(ZXParsedResultType)type {
  return [(ZXParsedResult *)[self alloc] initWithType:type];
}
```

**Comment by mrtristan** [comment]
@Westacular i'm with you here. definitely correct.

**Comment by aetherwu** [comment]
@Westacular It works, thanks!

**Comment by derekm92** [comment]
Thanks!
