### ISSUE TITLE
pod update takes > 30 minutes

### ISSUE THREAD

**Issue by radgid** [TheLevelUp/ZXingObjC#214]
pod install/update is very slow on ZXingObjC
"Installing ZXingObjC 3.1.0 (was 3.0.4)" takes more than 30 minutes
Are there some examples/test in the repo that can be pruned from the repo ?

**Comment by cwalcott** [comment]
The bulk of the size is taken up by the blackbox test images. Unfortunately removing them from the repository wouldn't speed up the download because they would still be in the history of the repo. As far as I know the only way to speed it up would be to erase them from the entire history of the project which I'm not comfortable doing.

**Comment by radgid** [comment]
Is it possible to crete additional pod spec - ZXingObjC-Prod - which will not have the test images, just the functionality required to use it in production ?
I mean if someone links to default ZXingObjC, wants to run the test etc they will use the default cocoapod. In the production deployment (automated builds with jenkins ...) the Prod version can be linked to instead.
