### ISSUE TITLE
iOS use *without* Pods?

### ISSUE THREAD

**Issue by DonMag** [TheLevelUp/ZXingObjC#233]
I'd like to incorporate this into an existing iOS project - which does NOT use Pods. Any tips on building the iOS sim+os / debug+release libs?

**Comment by qianyanseu** [comment]
Same issue here. Whenever I add `#import "ZXingObjC.h"`, Xcode says cannot find interface declaration for NSObject in ZXingObjC source code.

**Comment by reejosamuel** [comment]
This issue still exists and can't figure out how to resolve it.

**Comment by benjohnde** [comment]
Sadly I can not reproduce this. Maybe you added ZXingObjC as folder reference and not group reference? You also added ZXingObjC to your targets?

**Comment by qianyanseu** [comment]
@benjohnde I dragged ZXingObjC into 'Project Navigator' and checked 'copy items if needed'. 

Not sure what do you mean by add it to targets.

**Comment by benjohnde** [comment]
@qianyanseu sry for late answer. The colour of the folders was blue?

What I mean: you have basically two options to add a folder (and its containing subfolders/files) to an existing Xcode project:

i) Create groups
ii) Create folder references

You also can specify the targets to which the source files should be added.

You need to check your target (I guess you did that) and to use i) "Create groups". Otherwise Xcode won't find the header files of zxingobjc.

It works perfectly fine for me.

**Comment by qianyanseu** [comment]
@benjohnde Thanks! That must have been the issue.

**Comment by benjohnde** [comment]
You're welcome :)
