### ISSUE TITLE
ZXCapture rotation not rotating

### ISSUE THREAD

**Issue by sergiom88** [TheLevelUp/ZXingObjC#260]
in iPad I need the camera to be in landscape mode, I try applying rotation but has no effect at all. Always shows in portrait.

    captureScanner = [[ZXCapture alloc] init];

    captureScanner.camera = [captureScanner back];
    captureScanner.focusMode = AVCaptureFocusModeContinuousAutoFocus;
    captureScanner.rotation = 90.0f;            
    captureScanner.layer.frame = CGRectMake(0, 0, width, height);

why not allow to set an orientation?

    captureScanner.videoOrientation = AVCaptureVideoOrientationLandscapeRight

and in the ZXCapture class handle it when getting the layer using:

    layer.connection.videoOrientation = self.videoOrientation

**Comment by benjohnde** [comment]
I may get you wrong, but you have a camera preview in your ViewController. So you want to rotate this preview or you want the barcode scanner to read vertical instead of horizontal barcodes?

The latter one can be achieved by setting the rotation, like you did. But in portrait mode, IIRC you need to rotate the image bei 90 degree as the default byteArray is from the image in landscape mode. Thus you would scan vertically. So I would recommend to set the rotation to either 0.0f or 180.0f.

Hope this helps you :)

**Comment by AlmightyCZ** [comment]
You need to set transform as described here: https://github.com/TheLevelUp/ZXingObjC/issues/30 but it works for me only for the first time, when I'm changing the transform angle in a UIDeviceOrientationDidChangeNotification handler it doesn't work as expected :-(

**Comment by AlmightyCZ** [comment]
Ok update: the problem was in an "old" value of `[UIApplication sharedApplication].statusBarOrientation` property. When I use `[UIDevice currentDevice].orientation` or dispatch_async the call of handler, it works just fine.

**Comment by sergiom88** [comment]
yup for some reason rotation wasn't working. Had to use transform instead and set the frame size after rotating.
Thanks

**Comment by AlmightyCZ** [comment]
AFAIK rotation property only comes in play when the library is decoding barcode, i.e. it tells the library what orientation of barcode to expect.
