### ISSUE TITLE
iOS Swift Project - Some barcodes are not detected (sample project)

### ISSUE THREAD

**Issue by tkohub** [TheLevelUp/ZXingObjC#290]
Hello everyone.

i took the example BarcodeScanner from the project and scanning the following barcode (just one example) worked perfectly: https://www.activebarcode.de/codes/code128.html

When i take the ViewController from the sample project and move it to a brand new swift project (bridging header etc) the barcode is not detected at all. See sample project: 
https://www.dropbox.com/s/ubf254eoyui5z3z/TestZXing.zip?dl=0

It would be great if some can help out who has more experience with this project. It's quite hard to find the right direction here. I brought everything to the most simple use case, so i hope it is easier to find the issue.

Thank you!

Best,
Tobias

**Comment by kulack** [comment]
Not sure if you're still having this problem but I hit one like this too.

I had similar problems and found it to be related to the default camera resolution and the scaling factor the codes were not being scanned from the correct location in the video. The calculation in the applyRectOfInterest() was wrong because it depended on a couple of things that weren't true. I changed mine to this and got it to work pretty quickly. I'm having a few scanning problems now with the default very LOW resolution selected for the camera. 

Here's my applyRectOfInterest() function. It contains changes related to:
- Use self.capture.captureDevice.activeFormat.formatDescription to retrieve the real resolution of the video instead of hardcoding some presets. This code requires that the to scan be active/started
- Got rid of the landscape orientation, my app doesn't allow that
- Got rid off the offset calculation, that was overly complex and wrong in ways that I couldn't determine, my self.scanRectView object had the correct offset after the scaling and transformation was done.
- I left some NSLog entries in for you hope that helps.

```
    - (void)applyRectOfInterest:(UIInterfaceOrientation)orientation {
         NSLog(@"%s %ld", __PRETTY_FUNCTION__, (long)orientation);
        CGFloat /*scaleVideo,*/ scaleVideoX, scaleVideoY;
        CGFloat videoSizeX, videoSizeY;
        NSLog(@"%s Main frame: at %f, %f size %f x %f", __PRETTY_FUNCTION__,
              self.view.frame.origin.x, self.view.frame.origin.y,
              self.view.frame.size.width, self.view.frame.size.height);
        CGRect transformedVideoRect = self.scanRectView.frame;
        NSLog(@"%s Starting video frame: at %f, %f size %f x %f", __PRETTY_FUNCTION__,
              transformedVideoRect.origin.x, transformedVideoRect.origin.y,
              transformedVideoRect.size.width, transformedVideoRect.size.height);
        NSLog(@"%s Center of video frame is at %f, %f", __PRETTY_FUNCTION__,
              self.scanRectView.center.x, self.scanRectView.center.y);
        CMFormatDescriptionRef format = self.capture.captureDevice.activeFormat.formatDescription;
        CMVideoDimensions dim = CMVideoFormatDescriptionGetDimensions(format);
        videoSizeX = dim.width;
        videoSizeY = dim.height;
        NSLog(@"%s Video size:%f x %f", __PRETTY_FUNCTION__, videoSizeX, videoSizeY);
        if(UIInterfaceOrientationIsPortrait(orientation)) {
            scaleVideoX = self.view.frame.size.width / videoSizeX;
            scaleVideoY = self.view.frame.size.height / videoSizeY;
        } else {
            NSLog(@"%s We don't run in landscape yet", __PRETTY_FUNCTION__);
            abort();
        }
        NSLog(@"%s scaling capture size by %f %f", __PRETTY_FUNCTION__, 1/scaleVideoX, 1/scaleVideoY);
        _captureSizeTransform = CGAffineTransformMakeScale(1/scaleVideoX, 1/scaleVideoY);
        CGRect scanRect = CGRectApplyAffineTransform(transformedVideoRect, _captureSizeTransform);
        self.capture.scanRect = scanRect;
        NSLog(@"%s Final scanRect: at %f, %f size %f x %f within video %f x %f", __PRETTY_FUNCTION__,
              scanRect.origin.x, scanRect.origin.y,
              scanRect.size.width, scanRect.size.height,
              videoSizeX, videoSizeY);
    }
```
