### ISSUE TITLE
Zxing support for Swift 4 and Xcode9

### ISSUE THREAD

**Issue by FahdSaif** [TheLevelUp/ZXingObjC#369]
Hi Team,

Do we have ZXing support for xcode9.2 and swift4, we are planning to use it in our app development on IOS.

Regards,
Fahd

**Comment by FahdSaif** [comment]
Ben, is closed a response?

**Comment by benjohnde** [comment]
> ZXingObjC requires Xcode 8.3.3, targeting either iOS 8.0 and above, or Mac OS X 10.8 Mountain Lion and above.

Well I should correct that, Xcode 8.3.3 or above. ZXingObjC is working with Xcode 9.2 and Swift 4.

**Comment by eonist** [comment]
Any update on the swift version?

**Comment by benjohnde** [comment]
What exactly do you want to know? :) It is fully compatible with Swift.

**Comment by eonist** [comment]
@benjohnde Right. Miss read that. Thought you were working on a pure swift version.

May I ask: Does ZXingObjC enable you to get more granular information from a QR. Like 2d Array of black and white squares In the QR. I am asking because Im working on a HCCQR project. "High capacity color qr"

Thanks in advance. If you don't have time to answer its alright. ✌️

**Comment by benjohnde** [comment]
I do work on a Swift version, but it will take until January or February, cf. [zxingify](https://github.com/zxingify).

Yeah sure, it it possible to retrieve a `ZXByteMatrix` which is basically what you asked for.
https://github.com/TheLevelUp/ZXingObjC/blob/master/ZXingObjC/qrcode/decoder/ZXQRCodeDecoder.m#L54
