### ISSUE TITLE
ZXCGImageLuminanceSourceInfo.h cannot found

### ISSUE THREAD

**Issue by THaliloglu** [TheLevelUp/ZXingObjC#452]
Got build fail from ZXLuminanceSource.h with ZXCGImageLuminanceSourceInfo.h not found error.

carthage : github "TheLevelUp/ZXingObjC" ~> 3.6

**Comment by lisafly2014** [comment]
I met the same problem

**Comment by benjohnde** [comment]
Could you maybe send a verbose log or the full xcodebuild output? With carthage `0.31.2` I do not face the same problem.

**Comment by lisafly2014** [comment]
I know the problem.  It's because ZXCGImageLuminanceSourceInfo.h is not in public. 

issue for iOS Framework:

 Select   Framework Targets, then select "Build Phases", search "info"  in the filter. You will find header file "ZXCGImageLuminanceSourceInfo.h" in the project subsection.

Solution:
Drag "ZXCGImageLuminanceSourceInfo.h" from project to public subsection. Then "ZXCGImageLuminanceSourceInfo.h not found" error will be solved.

**Comment by lisafly2014** [comment]
Please help update the fixed commit

**Comment by benjohnde** [comment]
Should be fixed @lisafly2014. Could you respond shortly if everything works now as intended?

**Comment by benjohnde** [comment]
@siemensikkema super! :)

**Comment by benjohnde** [comment]
thanks for the feedback!

**Comment by THaliloglu** [comment]
Thanks @benjohnde, it's working now 👍
